/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Hassan Abd Eltawab
 ******************************************************************************
*/


#include"Stm32_F103C6_gpio_driver.h"
#include"Stm32_F103C6_EXTI_driver.h"
typedef volatile unsigned int vuint32_t;
#include<stdio.h>
#include <lcd.h>
#include"keypad.h"

void my_wait(int time){
	unsigned int x ,y ;
	for (x=0;x<time;x++){
		for(y=0;y<255;y++){
	}
}
}
void EXTI9_CallBack(void){
	LCD_WRITE_STRING("EXTI9 IS HAPPENED _|- ");
	my_wait(1000);
	LCD_clear_screen();
}
int main(){
	//Enable Clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
	//LCD preparing
//	LCD_INIT();
	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG={EXTI9PB9,EXTI_Trigger_RISING,EXTI_IRQ_Enable,EXTI9_CallBack};
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	/*  Loop forever */

	for(;;){

	}
	return 0;
}
