/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




/* ====================== Includes =========================== */
#include "STM32_F103C6_GPIO_Driver.h"


/* ========== Prototypes ========= */
void clock_init();
void GPIO_Init();
void delay(unsigned int x);

/* =========== Main Program ========== */
int main(void)
{
	clock_init();
	GPIO_Init();

	while(1)
	{
		// Check PortA pin1 --> connected with external PUR
		if (MCAL_GPIO_ReadPin(GPIO_PORTA, GPIO_PIN_1) == 0) // Push button pressed. 0 due to pull up
		{
			MCAL_GPIO_TogglePin(GPIO_PORTB, GPIO_PIN_1);
			while (MCAL_GPIO_ReadPin(GPIO_PORTA, GPIO_PIN_1) == 0);  // single press
		}

		// Check PortA pin13 --> connected with external PDR
		if (MCAL_GPIO_ReadPin(GPIO_PORTA, GPIO_PIN_13) == 1)  // Push button pressed. 1 due to pull down
		{
			// Multi Press
			MCAL_GPIO_TogglePin(GPIO_PORTB, GPIO_PIN_13);
		}
		delay(2);
	}
}

/* ======== clock init definition ======= */
void clock_init()
{
	// Enable clock of Port A
	RCC_GPIO_PORTA_CLK_EN();

	// Enable clock of Port B
	RCC_GPIO_PORTB_CLK_EN();
}

/* ======= GPIO init definition ======== */
void GPIO_Init()
{
	GPIO_PinConfig_t PinCfg;

	//PA1 input HighZ Floating input (reset state)
	PinCfg.GPIO_Pin_Number = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLOATING;
	MCAL_GPIO_Init(GPIO_PORTA, &PinCfg);


	// Port B -> pin 1 -> output ( push-pull mode )
	// CNF : 00 General purpose output push-pull
	// 01 : Output mode maximum speed 10 MHz
	PinCfg.GPIO_Pin_Number = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIO_PORTB, &PinCfg);



	// Port A -> pin 13 -> input ( High impedance = floating )
	PinCfg.GPIO_Pin_Number = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLOATING;
	MCAL_GPIO_Init(GPIO_PORTA, &PinCfg);



	// Port B -> pin 13 -> output ( push-pull mode )
	PinCfg.GPIO_Pin_Number = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIO_PORTB, &PinCfg);

}

void delay(unsigned int x)
{
	unsigned int i, j;
	for (i = 0;i < x; i++)
	{
		for (j = 0; j < 255; j++);
	}

}
