/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
//Mahmoud Elkot    -->>>>DATE: 10/30/2021

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// register address
#define GPIOA_BASE     0x40010800
#define GPIOA_CRH      *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL      *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR      *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA13         (1UL<<13)


#define RCC_BASE       0x40021000
#define RCC_APB2ENR    *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN     (1<<2)
//#define RCC_CFGR       *(volatile uint32_t *)(RCC_BASE + 0x04)
//#define RCC_CR         *(volatile uint32_t *)(RCC_BASE + 0x0)

#define NVIC_EXTI0   *(volatile uint32_t *)(0XE000E100)
//EXTI
#define  EXTI_BASE  0x40010400
#define EXTI_IMR   *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR  *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR   *(volatile uint32_t *)(EXTI_BASE + 0x14)   //          0x14

//AFIO module
#define     AFIO         0x40010000
#define AFIO_EXTICR1   *(volatile uint32_t *)(AFIO  + 0x08)

void clock_init(){
	//enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPAEN;
	//Enable clock for AFIO
	RCC_APB2ENR |= 1<<0;
}
void GPIO_INIT(){
	// Init GPIOA
		GPIOA_CRH &= 0XFF0FFFFF;
		GPIOA_CRH |= 0x00200000;
		GPIOA_CRL |= 1<<2;
}

int main (void)
{
	/// PA0 to EXTI LINE 0
		AFIO_EXTICR1 = 0;
	//rising edge
	EXTI_RTSR |= (1<<0);
	//enable external interrupt line 0
	EXTI_IMR |= (1<<0);

	//Enable NVIC
	NVIC_EXTI0 |=1<<6;
	 clock_init();
	 GPIO_INIT();
while(1){


    }
}
void EXTI0_IRQHandler(){
	//IRQ IS happened EXTI0 >> PORTA PIN0 | Rising edge
	//toggle led
	GPIOA_ODR ^=GPIOA13;
//clear pending register
	EXTI_PR |=1<<0; // clear interrupt line 0 WTC (WRITE ONE TO CLEAR)

}
